### ISSUE TITLE
Plotting multiple lines

### ISSUE THREAD

**Issue by alynaj36** [osianSmith/LineChartExample#1]
Hello Osian!

So I'm a college student in the USA who's working on a project to plot some data in xcode (using a line graph, it's due in a few weeks) but it requires me to give the user the option to plot multiple lines. I looked at the comments on your post and I was trying to figure out how to do that with your LineChart project but it doesn't seem to be working. I created a new text field and store its values in a new array. Then I basically repeat the same thing you do in line1 for line2 (with and without creating a new LineChartData() object) but it keeps overwriting the original data from line1 when I do data.addDataSet(line2). I don't get why it's not appending it to the first object? I guess I just don't understand how to add a new line step by step to the LineChartData object. How would I go about this differently? Thank you!

**Comment by osianSmith** [comment]
You need a new [ChartDataEntry] for the new data line that passed with a label to LineChartDataSet and added via ata.addDataSet(line2)

**Comment by alynaj36** [comment]
That's exactly what I do: 


    func updateGraph(){
        var lineChartEntry  = [ChartDataEntry]() //this is the Array that will eventually be displayed on the graph.
        var secondLineChartEntry = [ChartDataEntry]()
        
        //here is the for loop
        for i in 0..<nums.count {
            
            let value = ChartDataEntry(x: Double(i), y: nums[i]) // here we set the X and Y status in a data chart entry
            let value2 = ChartDataEntry(x: Double(i), y: nums[i]+1) //just to have non-overlapping values

            lineChartEntry.append(value) // here we add it to the data set
            secondLineChartEntry.append(value2)
        }

        
        let line1 = LineChartDataSet(values: lineChartEntry, label: "Number") //Here we convert lineChartEntry to a LineChartDataSet
        line1.colors = [NSUIColor.blue] //Sets the colour to blue
        
        let line2 = LineChartDataSet(values: secondLineChartEntry, label: "Number2")
        line2.colors = [NSUIColor.red]
        
        let data = LineChartData() //This is the object that will be added to the chart
        
        data.addDataSet(line1) //Adds the line to the dataSet
        data.addDataSet(line2)

        
       
        chart.data = data //finally - it adds the chart data to the chart and causes an update

        chart.chartDescription?.text = "My awesome chart" // Here we set the description for the graph
    }

**Comment by osianSmith** [comment]
Which object are you trying to append to?

**Comment by alynaj36** [comment]
I actually figured it out. I'll let you know if there's anymore questions! Thank you
